# Generated by Django 5.1.5 on 2026-08-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_groups_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='aa@gmail.com', max_length=255, verbose_name='email address'),
        ),
    ]
