# Generated by Django 5.1.5 on 2025-08-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('github', models.URLField()),
                ('instagram', models.URLField()),
                ('channel_telegram', models.URLField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='information')),
            ],
        ),
    ]
