# Generated by Django 5.1.5 on 2025-02-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='information'),
        ),
    ]
