# Generated by Django 5.1.5 on 2025-02-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='view',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
